# Generated by Django 6.0.3 on 2026-03-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_service_organizationservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='default', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('health', 'Health'), ('protection', 'Protection'), ('food', 'Food'), ('vaccination', 'Vaccination'), ('logistics', 'Logistics Support'), ('emergency', 'Emergency Response'), ('water', 'Water and Sanitation'), ('education', 'Education'), ('legal', 'Legal Assistance'), ('shelter', 'Shelter')], default='shelter', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrganizationTargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_groups', to='organizations.organization')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organizations.targetgroup')),
            ],
            options={
                'unique_together': {('organization', 'target_group')},
            },
        ),
    ]
