# Generated by Django 6.0.3 on 2026-04-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_organization_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
