# Generated by Django 6.0.3 on 2026-04-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
