# Generated by Django 6.0.3 on 2026-04-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
