# Generated by Django 6.0.3 on 2026-04-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organization_title_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(default='False', upload_to='organizations/icon/'),
            preserve_default=False,
        ),
    ]
