# Generated by Django 6.0.3 on 2026-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_familycategory_refugeefamilymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugeeprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
