# Generated by Django 6.0.3 on 2026-03-10 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_volunteerapplication'),
        ('organizations', '0003_targetgroup_organization_email_organization_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='selected_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='volunteerapplication',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization_application'),
        ),
    ]
