# Generated by Django 6.0.3 on 2026-03-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_volunteerapplication_selected_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='phone_number',
            field=models.CharField(default='0000', max_length=15),
            preserve_default=False,
        ),
    ]
