# Generated by Django 6.0.3 on 2026-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_volunteerapplication_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
