# Generated by Django 6.0.3 on 2026-03-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_volunteerprofile_skills'),
        ('organizations', '0003_targetgroup_organization_email_organization_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='organization_service',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='selected_services',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='selected_services',
            field=models.ManyToManyField(related_name='volunteer_applications', to='organizations.organizationservice'),
        ),
    ]
