# Generated by Django 6.0.3 on 2026-03-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_volunteerapplication_organization_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='rejection_reason',
        ),
    ]
