# Generated by Django 6.0.3 on 2026-03-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_volunteerapplication_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugeeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
