# Generated by Django 6.0.3 on 2026-03-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_refugeeprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
