# Generated by Django 6.0.3 on 2026-03-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_volunteerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
