# Generated by Django 6.0.3 on 2026-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_volunteerprofile_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='full_name',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
