# Generated by Django 6.0.3 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_volunteerprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='pin_expires_at',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='verification_pin',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='pin_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='verification_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
