# Generated by Django 6.0.3 on 2026-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_volunteerapplication_pin_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugeeprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
