# Generated by Django 5.2.6 on 2026-05-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_accept_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugeeprofile',
            name='profile_completed',
        ),
    ]
