# Generated by Django 5.2.6 on 2026-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_refugeeprofile_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugeeprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
