# Generated by Django 5.2.6 on 2026-05-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_refugeeprofile_profile_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefugeeFamilyMember',
        ),
    ]
