# Generated by Django 5.2.6 on 2026-05-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_delete_refugeefamilymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefugeeFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('family_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.familycategory')),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='accounts.refugeeprofile')),
            ],
            options={
                'unique_together': {('refugee', 'family_category')},
            },
        ),
    ]
