# Generated by Django 6.0.3 on 2026-03-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='service_request_id',
            new_name='aid_request',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='volunteer_id',
            new_name='volunteer',
        ),
    ]
