# Generated by Django 6.0.3 on 2026-03-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_rename_service_request_id_task_aid_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='aid_request',
            new_name='service_request_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='volunteer',
            new_name='volunteer_id',
        ),
    ]
