# Generated by Django 6.0.3 on 2026-03-16 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_targetgroup_organization_email_organization_password_and_more'),
        ('requests', '0003_rename_aid_request_task_service_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
    ]
