# Generated by Django 6.0.3 on 2026-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_servicerequest_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicerequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(default='syria', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='longitude',
        ),
    ]
