# Generated by Django 6.0.3 on 2026-03-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='required_resources',
        ),
    ]
