# Generated by Django 6.0.3 on 2026-04-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_remove_task_required_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
