# Generated by Django 6.0.3 on 2026-04-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_servicerequest_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='received_at',
        ),
    ]
