# Generated by Django 6.0.3 on 2026-04-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_remove_servicerequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
