# Generated by Django 6.0.3 on 2026-04-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_servicerequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
