# Generated by Django 6.0.3 on 2026-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_task_report_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='urgency_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10),
        ),
    ]
