# Generated by Django 5.2.6 on 2026-05-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_alter_servicerequest_urgency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
