# Generated by Django 5.2.6 on 2026-05-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_alter_servicerequest_id_alter_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_date',
        ),
    ]
