# Generated by Django 5.2.6 on 2026-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_remove_servicerequest_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
