# Generated by Django 5.2.6 on 2026-05-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_servicerequest_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_date',
        ),
    ]
