# Generated by Django 6.0.3 on 2026-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_servicerequest_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
